### PR TITLE
Prevent panic from goinfo on Windows

### LINKED ISSUE #228: Overwrite name for vhdl lexer
vhdl lexer is differently named in chroma (`VHDL`) and pygments (`vhdl`). This needs to be handled in wakatime-cli, to keep consistency with the python cli and ensure we send the pygments name to the backend.

### LINKED ISSUE #228: WakaTime Error in Visual Studio Code - Windows 10
**Visual Studio Debug**
```
Search "[WakaTime]" (13 hits in 1 file of 1 searched)
  C:\Users\ADunsmoor\Downloads\vscode-app-1630504212594.log (13 hits)
	Line 331: console.ts:137 [Extension Host] [WakaTime][DEBUG] Initializing WakaTime v17.0.0
	Line 377: console.ts:137 [Extension Host] [WakaTime][DEBUG] Current wakatime-cli version is v1.22.0
	Line 378: console.ts:137 [Extension Host] [WakaTime][DEBUG] Checking for updates to wakatime-cli...
	Line 380: console.ts:137 [Extension Host] [WakaTime][DEBUG] GitHub API Response 304
	Line 381: console.ts:137 [Extension Host] [WakaTime][DEBUG] wakatime-cli is up to date
	Line 382: console.ts:137 [Extension Host] [WakaTime][DEBUG] WakaTime initialized.
	Line 383: console.ts:137 [Extension Host] [WakaTime][DEBUG] Status bar icon enabled.
	Line 384: console.ts:137 [Extension Host] [WakaTime][DEBUG] Fetching coding activity for Today from api: C:\Users\ADunsmoor\.wakatime\wakatime-cli-windows-amd64.exe --today --plugin "\"vscode/1.59.1 vscode-wakatime/17.0.0\"" --config C:\Users\ADunsmoor\.wakatime.cfg --logfile C:\Users\ADunsmoor\.wakatime.log
	Line 392: console.ts:137 [Extension Host] [WakaTime][ERROR] Error: Command failed: C:\Users\ADunsmoor\.wakatime\wakatime-cli-windows-amd64.exe --today --plugin "vscode/1.59.1 vscode-wakatime/17.0.0" --config C:\Users\ADunsmoor\.wakatime.cfg --logfile C:\Users\ADunsmoor\.wakatime.log
	Line 413: console.ts:137 [Extension Host] [WakaTime][DEBUG] Error fetching today coding activity (1); Check your C:\Users\ADunsmoor\.wakatime.log file for more details
	Line 421: console.ts:137 [Extension Host] [WakaTime][DEBUG] Sending heartbeat: C:\Users\ADunsmoor\.wakatime\wakatime-cli-windows-amd64.exe --entity c:\Users\ADunsmoor\Documents\GitHub\EVC\8300\EVC8365\client\src\app\please-wait\please-wait.component.ts --plugin "\"vscode/1.59.1 vscode-wakatime/17.0.0\"" --alternate-project EVC8365 --config C:\Users\ADunsmoor\.wakatime.cfg --log-file C:\Users\ADunsmoor\.wakatime.log
	Line 422: console.ts:137 [Extension Host] [WakaTime][ERROR] Error: Command failed: C:\Users\ADunsmoor\.wakatime\wakatime-cli-windows-amd64.exe --entity c:\Users\ADunsmoor\Documents\GitHub\EVC\8300\EVC8365\client\src\app\please-wait\please-wait.component.ts --plugin "vscode/1.59.1 vscode-wakatime/17.0.0" --alternate-project EVC8365 --config C:\Users\ADunsmoor\.wakatime.cfg --log-file C:\Users\ADunsmoor\.wakatime.log
	Line 443: console.ts:137 [Extension Host] [WakaTime][ERROR] Unknown Error (1); Check your C:\Users\ADunsmoor\.wakatime.log file for more details
```
**.wakatime.log**
```
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:58","func":"Run","level":"debug","message":"command: version","now":"2021-09-01T08:54:08-05:00","version":"v1.22.0"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:76","func":"Run","level":"debug","message":"command: today","now":"2021-09-01T08:54:09-05:00","version":"v1.22.0"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:88","func":"Run","level":"debug","message":"command: heartbeat","now":"2021-09-01T08:54:48-05:00","version":"v1.22.0"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/heartbeat/heartbeat.go:85","func":"SendHeartbeats","level":"debug","message":"heartbeat params: category: 'coding', cursor position: '', entity: 'c:\\Users\\ADunsmoor\\Documents\\GitHub\\EVC\\8300\\EVC8365\\client\\src\\app\\please-wait\\please-wait.component.ts', entity type: 'file', num extra heartbeats: 0, is write: false, language: '', line number: '', lines in file: '', offline disabled: false, offline queue file: '', offline sync max: 1000, time: 1630504488.35987, api params: (api key: '77db...', api url: 'https://api.wakatime.com/api/v1', backoff at: '', backoff retries: 0, hostname: 'PC123', plugin: 'vscode/1.59.1 vscode-wakatime/17.0.0', timeout: 2m0s, disable ssl verify: false, proxy url: '', ssl cert filepath: ''), filter params: (exclude: '[]', exclude unknown project: false, include: '[]', include only with project file: false), project params: (alternate: 'EVC8365', disable submodule: '[]', map patterns: '[]', override: ''), sanitize params: (hide branch names: '[]', hide file names: '[]', hide project names: '[]')","now":"2021-09-01T08:54:48-05:00","version":"v1.22.0"}
```
Uninstalling and re-installing the plugin does not help.  My WakaTime API key is set.  A linux laptop on the same network is working fine with VS Code and WakaTime using the same account.  This randomly happened to me on Windows.  I have been using it fine without issues for months.

### PR DESCRIPTION
**Pull request by alanhamlett**
Fixes wakatime/vscode-wakatime#228.

### CODE REVIEW

File: pkg/heartbeat/heartbeat.go [hunk 1]
```diff
@@ -167,7 +167,7 @@ func UserAgentUnknownPlugin() string {
 // UserAgent generates a user agent from various system infos, including a
 // a passed in value for plugin.
 func UserAgent(plugin string) string {
-	info := goInfo.GetInfo()
+	info, _ := goInfo.GetInfo() // TODO: log this error to debug log
```
Comment (gandarez) [inline pkg/heartbeat/heartbeat.go]: Error should be handled here.

**Review by gandarez — CHANGES_REQUESTED** [review]

File: pkg/heartbeat/heartbeat.go (hunk 1 above)
Comment (alanhamlett) [reply pkg/heartbeat/heartbeat.go]: Done.

File: pkg/heartbeat/heartbeat.go [hunk 2]
```diff
@@ -167,7 +167,10 @@ func UserAgentUnknownPlugin() string {
 // UserAgent generates a user agent from various system infos, including a
 // a passed in value for plugin.
 func UserAgent(plugin string) string {
-	info := goInfo.GetInfo()
+	info, err := goInfo.GetInfo() // TODO: log this error to debug log
```
Comment (gandarez) [inline pkg/heartbeat/heartbeat.go]: Forgot to remove "TODO" here.

**Review by gandarez — APPROVED** [review]
One small remark on the code. Would be good to squash these 3 commits into a single one and `force push`. Squashing using GH won't work for us.

File: pkg/heartbeat/heartbeat.go (hunk 2 above)
Comment (alanhamlett) [reply pkg/heartbeat/heartbeat.go]: Oops, thanks!
