### PR TITLE
Fix unhandled default params

### LINKED ISSUE #1147: --heartbeat-rate-limit-seconds flag is not properly configured in the config file
I’m using the VSCode extension, and even though I set `heartbeat_rate_limit_seconds = 10` in the `wakatime.cfg` file, it seems that the actual `heartbeat_rate_limit_seconds` is being set to the default value of 120.  

Looking at the code, it appears that the `heartbeat_rate_limit_seconds` value from `wakatime.cfg` is only read if the flag is explicitly set to 0. This behavior feels more like a bug than an intended design.  

Additionally, even though I’ve set `debug = true`, I’m unable to see any debug logs. I’ve already made a simple fix for this issue and submitted a PR. Please let me know if I’ve missed anything.

I recently discovered WakaTime and thought it would be fun to show, in near real-time, what code I’m working on through my blog.  So I hope this issue gets resolved soon!

**Environment**:

- OS: mac os 15.1.1(24B91)
- Platform: arm64

**Logs**:

### PR DESCRIPTION
**Pull request by gandarez**
This PR fixes unhandled default params when flag/config is not set. Currently any value informed from flag/config is completely ignored for `rate limit` and `timeout`.  The `vipertools.FirstNonEmptyInt()` function now checks if value is set and accepts zero as valid one.

Some tests have been added to ensure the right behavior and increase coverage.

Fixes #1147

### CODE REVIEW

File: cmd/params/params_test.go [hunk 1]
```diff
@@ -1863,7 +1908,7 @@ func TestLoadOfflineParams_RateLimit_NonIntegerValue(t *testing.T) {
 
 	params := cmdparams.LoadOfflineParams(context.Background(), v)
 
-	assert.Zero(t, params.RateLimit)
+	assert.Equal(t, time.Duration(offline.RateLimitDefaultSeconds)*time.Second, params.RateLimit)
```
Comment (gandarez) [inline cmd/params/params_test.go:1911]: Invalid values when set, should default to `offline.RateLimitDefaultSeconds`.

File: cmd/params/params.go [hunk 2]
```diff
@@ -1100,7 +1109,7 @@ func (p Offline) String() string {
 	}
 
 	return fmt.Sprintf(
-		"disabled: %t, last sent at: '%s', print max: %d, num rate limit: %d, num sync max: %d",
+		"disabled: %t, last sent at: '%s', print max: %d, rate limit: %s, num sync max: %d",
```
Comment (gandarez) [inline cmd/params/params.go:1113]: Correctly print `time.Duration` format.

File: cmd/params/params_test.go [hunk 3]
```diff
@@ -2255,19 +2303,15 @@ func TestLoadAPIParams_BackoffAtErr(t *testing.T) {
...
 
-	assert.Equal(t, cmdparams.API{
-		BackoffAt:      time.Time{},
-		BackoffRetries: 2,
-		Key:            "00000000-0000-4000-8000-000000000000",
-		URL:            "https://api.wakatime.com/api/v1",
-		Hostname:       "my-computer",
-	}, params)
+	assert.Equal(t, 2, params.BackoffRetries)
+	assert.Empty(t, params.BackoffAt)
```
Comment (gandarez) [inline cmd/params/params_test.go:2314]: Simplify the testing scope to what matters.

File: pkg/vipertools/vipertools.go [hunk 4]
```diff
@@ -31,9 +32,20 @@ func FirstNonEmptyInt(v *viper.Viper, keys ...string) (int, bool) {
...
+			continue
+		}
+
+		// Zero means a valid value when set, so it needs to use generic function and later cast it to int
+		value := v.Get(key)
+
+		// If the value is not an int, it will continue to find the next non-empty key
+		parsed, err := cast.ToIntE(value)
+		if err != nil {
+			continue
```
Comment (gandarez) [inline pkg/vipertools/vipertools.go:45]: if casting to int fails, then continue to next non-empty value if exists.

File: pkg/vipertools/vipertools_test.go [hunk 5]
```diff
@@ -66,7 +66,7 @@ func TestFirstNonEmptyInt_EmptyInt(t *testing.T) {
 	v := viper.New()
 	v.Set("first", 0)
 	_, ok := vipertools.FirstNonEmptyInt(v, "first")
-	assert.False(t, ok)
+	assert.True(t, ok)
```
Comment (gandarez) [inline pkg/vipertools/vipertools_test.go:69]: Zero values are now considered a valid ones when set.

File: main_test.go [hunk 6]
```diff
@@ -249,6 +249,88 @@ func TestSendHeartbeats_SecondaryApiKey(t *testing.T) {
 	assert.Eventually(t, func() bool { return numCalls == 1 }, time.Second, 50*time.Millisecond)
 }
 
+func TestSendHeartbeats_Timeout(t *testing.T) {
```
Comment (gandarez) [inline main_test.go:252]: New integration test to make sure it fails by timeout other than generic errors.

**Review by alanhamlett — APPROVED** [review]
