### PR TITLE
UrlEncode X-Machine-Name header

### LINKED ISSUE #250: net/http: invalid header field value for "X-Machine-Name"
I use two laptops, one of them works perfectly sending code activity to Wakatime. But the other one is not able.

Log details:

```
{"caller":"cmd/run.go:292","func":"cmd.runCmd","level":"error","message":"failed to run command: today fetch failed: failed fetching today from api: failed to make request to \"https://api.wakatime.com/api/v1/users/current/statusbar/today\": Get \"https://api.wakatime.com/api/v1/users/current/statusbar/today\": net/http: invalid header field value for \"X-Machine-Name\"","now":"2023-03-22T09:13:02-05:00","os/arch":"darwin/arm64","version":"v1.70.0"}
{"caller":"cmd/run.go:292","file":"/Users/andres.duque/Development/Buildertrend/bt-wallet-web-client/src/app/pages/Transactions/Transactions.component.tsx","func":"cmd.runCmd","level":"error","lineno":142,"message":"failed to run command: sending heartbeat(s) failed: api error: failed making request to \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": Post \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": net/http: invalid header field value for \"X-Machine-Name\"","now":"2023-03-22T09:13:38-05:00","os/arch":"darwin/arm64","plugin":"vscode/1.76.1 vscode-wakatime/24.0.7","time":1679494418.799427,"version":"v1.70.0"}
{"caller":"cmd/run.go:292","file":"/Users/andres.duque/Development/Buildertrend/bt-wallet-web-client/src/app/pages/Transactions/Transactions.component.tsx","func":"cmd.runCmd","is_write":true,"level":"error","lineno":130,"message":"failed to run command: sending heartbeat(s) failed: rate limited: won't send heartbeat due to backoff","now":"2023-03-22T09:14:13-05:00","os/arch":"darwin/arm64","plugin":"vscode/1.76.1 vscode-wakatime/24.0.7","time":1679494453.0279932,"version":"v1.70.0"}
{"caller":"cmd/run.go:292","file":"/Users/andres.duque/Development/Buildertrend/bt-wallet-web-client/src/app/pages/Transactions/Transactions.component.tsx","func":"cmd.runCmd","level":"error","lineno":126,"message":"failed to run command: sending heartbeat(s) failed: rate limited: won't send heartbeat due to backoff","now":"2023-03-22T09:16:51-05:00","os/arch":"darwin/arm64","plugin":"vscode/1.76.1 vscode-wakatime/24.0.7","time":1679494611.281213,"version":"v1.70.0"}
```

### PR DESCRIPTION
**Pull request by alanhamlett**
Fixes https://github.com/wakatime/jetbrains-wakatime/issues/250 by url encoding the `X-Machine-Name` header because it's value comes from user input.

The WakaTime API now urldecodes `X-Machine-Name` header on incoming heartbeats, deployed today.

### CODE REVIEW

File: pkg/api/option.go [hunk 1]
```diff
@@ -159,12 +148,27 @@ func WithTimeout(timeout time.Duration) Option {
 	}
 }
 
+// WithHostname sets the X-Machine-Name header to the passed in hostname.
+func WithHostname(hostname string) Option {
+	return func(c *Client) {
+		next := c.doFunc
+		c.doFunc = func(c *Client, req *http.Request) (*http.Response, error) {
+			hostname = url.QueryEscape(strings.TrimSpace(hostname))
```
Comment (gandarez) [inline pkg/api/option.go]: It should be done at `params.go` after this [line](https://github.com/wakatime/wakatime-cli/blob/develop/cmd/params/params.go#L264). The `hostname` is always parsed once when reading from input and like other variables we already "clean up/fomat" them.

File: pkg/api/option.go [hunk 2]
```diff
@@ -159,12 +148,27 @@ func WithTimeout(timeout time.Duration) Option {
...
+		}
+	}
+}
+
 // WithTimezone sets the TimeZone header to the passed in timezone.
 func WithTimezone(timezone string) Option {
 	return func(c *Client) {
 		next := c.doFunc
 		c.doFunc = func(c *Client, req *http.Request) (*http.Response, error) {
+			timezone = strings.TrimSpace(timezone)
```
Comment (gandarez) [inline pkg/api/option.go]: The idea can be done here. Here's [the piece of code](https://github.com/wakatime/wakatime-cli/blob/develop/cmd/api/api.go#L38-L43) that call `WithTimezone`.

File: pkg/heartbeat/heartbeat.go [hunk 3]
```diff
@@ -186,12 +186,12 @@ func UserAgent(plugin string) string {
 
 	return fmt.Sprintf(
 		"wakatime/%s (%s-%s-%s) %s %s",
-		version.Version,
-		system.OSName(),
-		info.Core,
-		info.Platform,
-		runtime.Version(),
-		plugin,
+		strings.TrimSpace(version.Version),
```
Comment (gandarez) [inline pkg/heartbeat/heartbeat.go]: it never returns a string with spaces.

File: pkg/api/option.go [hunk 4]
```diff
@@ -178,7 +182,9 @@ func WithUserAgent(plugin string) Option {
 	return func(c *Client) {
 		next := c.doFunc
 		c.doFunc = func(c *Client, req *http.Request) (*http.Response, error) {
+			userAgent = strings.TrimSpace(userAgent)
```
Comment (gandarez) [inline pkg/api/option.go]: Same here.

**Review by gandarez — CHANGES_REQUESTED** [review]
Requested some changes to make parsing flags the entry point to clean up or format strings.

**Review by pawnhearts — APPROVED** [review]

File: pkg/api/option.go (hunk 1 above)
Comment (alanhamlett) [reply pkg/api/option.go]: No, we should encode headers when making the request not when parsing params. This encoding is only for over the wire so we shouldn't do it early.

File: pkg/api/option.go (hunk 2 above)
Comment (alanhamlett) [reply pkg/api/option.go]: What should be done here?

Comment (alanhamlett) [reply pkg/api/option.go]: Fixed!

**Review by gandarez — APPROVED** [review]
