### PR TITLE
Fix project path if it was not auto-detected or alternate is taken

### LINKED ISSUE #209: `hide_project_folder` ignored
OS: Windows 10
IDE: Android Studio Chipmunk | 2021.2.1
WakaTime CLI version: v1.45.1
WakaTime Extension version: Latest(13.1.14) on <https://plugins.jetbrains.com/plugin/7425-wakatime/versions>
My `.wakatime.cfg`:

```ini
[settings]
hide_project_folder = true
exclude = .*
include = \
/programming/study/
api_key = ***
proxy = 
debug = true
status_bar_enabled = true
```

When I working on `C:\Users\${user}\programming\study\learn_flutter`, the full directory path is sent.
Maybe change below line to: `cmds.add("--alternate-project");` and publish new version of extension to store.
https://github.com/wakatime/jetbrains-wakatime/blob/afbeaf4cd1066a18c6787ca122bf80be2c1a663d/src/com/wakatime/intellij/plugin/WakaTime.java#L407

Thank you for your hard work.

### PR DESCRIPTION
**Pull request by gandarez**
This PR fixes project path if it was not auto-detected by any rev control or alternate is taken.

Fixes https://github.com/wakatime/jetbrains-wakatime/issues/209.

### CODE REVIEW

**Review by alanhamlett — CHANGES_REQUESTED** [review]
Should use this detection logic:

https://github.com/wakatime/wakatime-cli/compare/bugfix/project-path...bugfix/project-path-2

File: pkg/project/project.go [hunk 1]
```diff
@@ -28,78 +28,150 @@ const (
...
 
+type (
+	// Detecter is a common interface for project.
+	Detecter interface {
+		Detect() (Result, bool, error)
+		ID() DetectorID
+	}
+
+	DetecterArg struct {
+		Entity    string
```
Comment (alanhamlett) [inline pkg/project/project.go]: Let's change this to `Path string` because it's no longer an entity, it can be a project folder or entity path.

File: pkg/project/project.go [hunk 2]
```diff
@@ -28,78 +28,150 @@ const (
...
-						result.Project = firstNonEmptyString(result.Project, revControlResult.Project, h.ProjectAlternate)
-					}
+				// fourth, use alternate project
+				if result.Project == "" && h.ProjectAlternate != "" {
+					result.Project = h.ProjectAlternate
+					result.Folder = firstNonEmptyString(h.ProjectPathOverride, result.Folder)
 				}
 
+				// fifth, if no folder is found, use project folder or entity's path
+				result.Folder = firstNonEmptyString(result.Folder, h.ProjectPathOverride, filepath.Dir(h.Entity))
```
Comment (alanhamlett) [inline pkg/project/project.go]: Let's prevent obfuscating non-filetype:

```go
				result.Folder = firstNonEmptyString(result.Folder, h.ProjectPathOverride)

				if h.EntityType == heartbeat.FileType {
					result.Folder = firstNonEmptyString(result.Folder, filepath.Dir(h.Entity))
				}
```

Like in https://github.com/wakatime/wakatime-cli/compare/bugfix/project-path...bugfix/project-path-3.

**Review by alanhamlett — APPROVED** [review]
❤️ ❤️
