### PR TITLE
Catch panic from bbolt open connection

### LINKED ISSUE #848: panic: invalid freelist page: 0, page type is unknown<00>
### Environment

- OS: Windows
- Platform: amd64
- Plugin: idea/2022.3.2 idea-wakatime/14.1.3
- CLI: v1.68.1

### Stacktrace

```
goroutine 1 [running]:
runtime/debug.Stack()
 /opt/hostedtoolcache/go/1.19.6/x64/src/runtime/debug/stack.go:24 +0x65
github.com/wakatime/wakatime-cli/cmd.runCmd.func1()
 /home/runner/work/wakatime-cli/wakatime-cli/cmd/run.go:272 +0xd3
panic({0x9a5540, 0xc00060b980})
 /opt/hostedtoolcache/go/1.19.6/x64/src/runtime/panic.go:884 +0x212
go.etcd.io/bbolt.(*freelist).read(0x0?, 0x11bfa0c2000)
 /home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.7/freelist.go:267 +0x22e
go.etcd.io/bbolt.(*DB).loadFreelist.func1()
 /home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.7/db.go:415 +0xb8
sync.(*Once).doSlow(0xc000123608?, 0x10?)
 /opt/hostedtoolcache/go/1.19.6/x64/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
 /opt/hostedtoolcache/go/1.19.6/x64/src/sync/once.go:65
go.etcd.io/bbolt.(*DB).loadFreelist(0xc000123440?)
 /home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.7/db.go:408 +0x47
go.etcd.io/bbolt.Open({0xc0002fd260, 0x1a}, 0x0?, 0xc000378c20)
 /home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.7/db.go:290 +0x40c
github.com/wakatime/wakatime-cli/pkg/offline.pushHeartbeats({0xc0002fd260?, 0x5e?}, {0xc0000b0000, 0x3, 0x4})
 /home/runner/work/wakatime-cli/wakatime-cli/pkg/offline/offline.go:311 +0xb7
github.com/wakatime/wakatime-cli/pkg/offline.pushHeartbeatsWithRetry({0xc0002fd260, 0x1a}, {0xc0000b0000, 0x3, 0x4})
 /home/runner/work/wakatime-cli/wakatime-cli/pkg/offline/offline.go:293 +0xdd
github.com/wakatime/wakatime-cli/pkg/offline.WithQueue.func1.1({0xc0000b0000, 0x3, 0x4})
 /home/runner/work/wakatime-cli/wakatime-cli/pkg/offline/offline.go:67 +0x1b8
github.com/wakatime/wakatime-cli/pkg/filter.WithLengthValidator.func1.1({0xc0000b0000?, 0xc000378e70?, 0x194987?})
 /home/runner/work/wakatime-cli/wakatime-cli/pkg/filter/filter.go:56 +0x7d
github.com/wakatime/wakatime-cli/pkg/remote.WithCleanup.func1.1({0xc0000b0000, 0x3, 0x4})
 /home/runner/work/wakatime-cli/wakatime-cli/pkg/remote/remote.go:123 +0xb8
github.com/wakatime/wakatime-cli/pkg/heartbeat.WithSanitization.func1.1({0xc0000b0000, 0x3, 0x4})
 /home/runner/work/wakatime-cli/wakatime-cli/pkg/heartbeat/sanitize.go:36 +0xdb
github.com/wakatime/wakatime-cli/pkg/project.WithFiltering.func1.1({0xc0000b0900, 0x3, 0x0?})
 /home/runner/work/wakatime-cli/wakatime-cli/pkg/project/filter.go:45 +0xc9
github.com/wakatime/wakatime-cli/pkg/project.WithDetection.func1.1({0xc0000b0900?, 0x3?, 0x4?})
 /home/runner/work/wakatime-cli/wakatime-cli/pkg/project/project.go:215 +0x6b
github.com/wakatime/wakatime-cli/pkg/deps.WithDetection.func1.1({0xc0000b0900, 0x3, 0x4})
 /home/runner/work/wakatime-cli/wakatime-cli/pkg/deps/deps.go:77 +0xd3
github.com/wakatime/wakatime-cli/pkg/language.WithDetection.func1.1({0xc0000b0900, 0x3, 0x4})
 /home/runner/work/wakatime-cli/wakatime-cli/pkg/language/language.go:48 +0xb8
github.com/wakatime/wakatime-cli/pkg/filestats.WithDetection.func1.1({0xc0000b0900, 0x3, 0x4})
 /home/runner/work/wakatime-cli/wakatime-cli/pkg/filestats/filestats.go:72 +0xbf
github.com/wakatime/wakatime-cli/pkg/apikey.WithReplacing.func1.1({0xc0000b0900, 0x3, 0x4})
 /home/runner/work/wakatime-cli/wakatime-cli/pkg/apikey/apikey.go:42 +0xbc
github.com/wakatime/wakatime-cli/pkg/remote.WithDetection.func1.1({0xc0000b0480, 0x3, 0x0?})
 /home/runner/work/wakatime-cli/wakatime-cli/pkg/remote/remote.go:103 +0xc2
github.com/wakatime/wakatime-cli/pkg/filter.WithFiltering.func1.1({0xc0000b0000, 0x3, 0xc0000be1c0?})
 /home/runner/work/wakatime-cli/wakatime-cli/pkg/filter/filter.go:41 +0xc2
github.com/wakatime/wakatime-cli/pkg/heartbeat.WithEntityModifer.func1.1({0xc0000b0000, 0x3, 0x4})
 /home/runner/work/wakatime-cli/wakatime-cli/pkg/heartbeat/entity_modify.go:24 +0xb8
github.com/wakatime/wakatime-cli/pkg/heartbeat.WithFormatting.func1.1({0xc0000b0000, 0x3, 0x4})
 /home/runner/work/wakatime-cli/wakatime-cli/pkg/heartbeat/format.go:32 +0xbf
github.com/wakatime/wakatime-cli/pkg/heartbeat.NewHandle.func1({0xc0000b0000, 0x3, 0x4})
 /home/runner/work/wakatime-cli/wakatime-cli/pkg/heartbeat/heartbeat.go:168 +0xd1
github.com/wakatime/wakatime-cli/cmd/heartbeat.SendHeartbeats(0xc000240680, {0xc0002fd260, 0x1a})
 /home/runner/work/wakatime-cli/wakatime-cli/cmd/heartbeat/heartbeat.go:123 +0x77b
github.com/wakatime/wakatime-cli/cmd/heartbeat.Run(0xc35760?)
 /home/runner/work/wakatime-cli/wakatime-cli/cmd/heartbeat/heartbeat.go:36 +0xce
github.com/wakatime/wakatime-cli/cmd.runCmd(0xc000240680, 0x0, 0x0, 0xb35a10)
 /home/runner/work/wakatime-cli/wakatime-cli/cmd/run.go:288 +0x122
github.com/wakatime/wakatime-cli/cmd.RunCmdWithOfflineSync(0xc00039d5b0?, 0x11?, 0x86?, 0x0?)
 /home/runner/work/wakatime-cli/wakatime-cli/cmd/run.go:246 +0x26
github.com/wakatime/wakatime-cli/cmd.Run(0x0?, 0x0?)
 /home/runner/work/wakatime-cli/wakatime-cli/cmd/run.go:116 +0x5d7
github.com/wakatime/wakatime-cli/cmd.NewRootCMD.func1(0xc00014a300?, {0xa62ce8?, 0xf?, 0xf?})
 /home/runner/work/wakatime-cli/wakatime-cli/cmd/root.go:29 +0x1d
github.com/spf13/cobra.(*Command).execute(0xc00014a300, {0xc000112010, 0xf, 0xf})
 /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc00014a300)
 /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
 /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/wakatime/wakatime-cli/cmd.Execute()
 /home/runner/work/wakatime-cli/wakatime-cli/cmd/root.go:260 +0x1e
main.main()
 /home/runner/work/wakatime-cli/wakatime-cli/main.go:6 +0x17
```

### PR DESCRIPTION
**Pull request by gandarez**
This PR catches any panic from `bolt.Open` and log it as error or warning depending the context where it's called. This is a way to avoid breaking the cli when there's a corrupted bolt file. It also fixes few typos.

Closes #848

### CODE REVIEW

File: pkg/offline/error.go [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+}
+
+// Error method to implement error interface.
+func (e ErrOpenDB) Error() string {
+	return e.Err.Error()
+}
+
+// Message method to implement wakaerror.Error interface.
+func (e ErrOpenDB) Message() string {
+	return fmt.Sprintf("failed to open db connection: %s", e.Err)
```
Comment (alanhamlett) [inline pkg/offline/error.go]: let's remove the word `connection` here because people will think it means over a network when reading logs.

**Review by alanhamlett — APPROVED** [review]

**Comment by alanhamlett** [comment]
Ready to merge!
